### ISSUE TITLE
Dahlia Backend for Futil Tracker

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#101]
This issue keeps track of the state of the Dahlia backend for Futil. 

The Dahlia backend currently supports the subset of Dahlia that excludes unrolled `for` loops and memories and `view`s. 

- [x] Implement unrolling for `for` loops
- [x] Memory
  - [x] Write the library interface for memories in the `primitives/std.lib` file
  - [x] Implement the memories in Verilog
  - [x] Generate Futil memories for Dahlia memories
  - [x] Implement banked memories (presumably by making copies of Futil memories)
- [x] Implement views. The thing to do may be implementing Futil primitives for each Dahlia view.
