### ISSUE TITLE
Mux Insertion Tracker

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/futil#111]
This issue tracks the different mux insertion passes that are need.
- [ ] Par Remove by Mux Insertion #113 
- [ ] Seq mux insertion #116

**Comment by sgpthomas** [comment]
I'm realizing that this may not be possible to do in general. We probably should have a series of passes that do this in specialized cases. I'm going to turn this issue into a tracker for such specialized passes.

**Comment by sgpthomas** [comment]
- [ ] Par Remove by Mux Insertion #113

**Comment by sgpthomas** [comment]
- [ ] Par Remove by Mux Insertion #113

**Comment by rachitnigam** [comment]
Futil has been redesigned to use go/done holes and groups in #139.
