### ISSUE TITLE
Interpreter

### ISSUE THREAD

**Issue by kwf37** [cucapra/futil#88]
Here is a rough sketch of tasks for implementing the interpreter. We can continue tracking tasks and progress for it on this issue.

- [ ] `eval_s`: Implement evaluation/simulation of one step of a component's structure (i.e. one `enable` statement)
    * [ ] Needs to evaluate the inputs and outputs of primitive components- may require refactoring of primitive library. It may be nice to have a standard library of components defined in Rust instead of hard-coding standard library names. EDIT: I added a function `eval_lib` that can be implemented to simulate library components. This can be done by hard-coding standard library names for now, and then we can switch to a nicer library definition as we progress.
    * [x] Need to have an extra data structure for storing register and memory state during evaluation.
    * [x] Implement a topological sort graph traversal that works on cyclic graphs. Structure graphs can be cyclic due to sequential components like registers, but Petgraph's Topo sort raises an error on cyclic graphs. It also only seems to support traversal starting from a single node, but we probably want to start traversals with all input nodes on the stack.
 It will need to be able to store the state of all subcomponents as well.

- [ ] `eval_c`: Implement evaluation of a component's control- should be similar to standard big-step semantics. Evaluating an `enable` should call `eval_s` to simulate the structure.

**Comment by kwf37** [comment]
Notes on assumptions that I have made so far:

- The output ports of the component will take the output values from the last enable statement that runs in the control
- There should be no cycles in the structure graph except when using sequential primitives such as registers.
- Component input values are available to the component during all logical time steps.

I will keep this list updated as I go, and please let me know if there are points I should clarify.

**Comment by kwf37** [comment]
Short update: I believe all of the graph infrastructure is in place for simulating signals on a StructureGraph. Next I want to add features to main for visualizing the structure graph and making sure that these helpers are doing the right thing. Goal for the week is to be able to simulate and visualize single logical time steps to ensure the functions are working correctly.

Here are some notes on next few tasks:
- [ ] Generating state structure from a component (pretty straightforward)
- [ ] Adding interpreter options to cmdline for testing
- [ ] Interactive functions for stepping single timesteps
- [ ] Visualizing Structure graphs with dot as we implement the rest of the eval_s and eval_c structures. Should play around with petgraph::dot visualization options.
- [ ] Implement evaluation for primitives.
